export default function Head({ params }: { params: { project: string } }) {
  const { project } = params;

  return (
    <>
      <title>{project}</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
